### ISSUE TITLE
Color equality is not friendly

### ISSUE THREAD

**Issue by kvanberendonck** [macite/swingame#30]
It's annoying to write NUnit tests around SwinGameSDK.Color in C#;

```
		[Test ()]
		public void TestDefaultInitialisation ()
		{
			Drawing myDrawing = new Drawing ();

			Assert.AreEqual (myDrawing.Background.ToArgb(), Color.White.ToArgb());
		}
```

If you take away both of the `.ToArgb()` the test will always fail because Color.White returns a brand new color and the default implementation of `AreEqual` does a shallow equality which checks only the reference for equality.

[SwinGameSDK.Color needs to implement a better `Equal`](http://stackoverflow.com/a/318223/1220423)

**Comment by jgardner8** [comment]
I haven't actually looked into this after reading your post, so forgive me if I'm wrong. I don't think SwinGameSDK.Color is really intended to be used in the C# version of SwinGame, instead it is suggested you substitute System.Drawing.Color. All of the language versions of SwinGame are generated based on the Pascal version which is why SwinGameSDK.Color still exists. That also explains some of the weird things like the existence of the PointAt(x,y) method instead of just using the Point2D constructor.

**Comment by kvanberendonck** [comment]
I couldn't get `System.Drawing.Color` and `SwinGameSDK.Color` to cast between each other, so I've just been using the latter because it's the one I could make work.

**Comment by jgardner8** [comment]
Strange. Maybe we should look at fixing that rather than `SwinGameSDK.Color.Equals()`. If we modify the generated C# code it will be overwritten next time a Pascal update regenerates it anyway (unless there's some provision for that I'm not aware of, I haven't spent too much time working on SwinGame.)

**Comment by macite** [comment]
We have switched to our own Color class now so that we are not dependent on the .NET framework for this (it worked ok on Windows but not so much on Mac/Linux). 

I've made the requested changes and uploaded a new version. Comparisons for equality should work fine now, and I also cache the results so that future calls result in the same object for the predefined colors.

**Comment by kvanberendonck** [comment]
Thanks.

This will be an interesting one to talk about on the COS20007 report :)
